import { Artifact } from "../lib/content/schemas";

export const artifacts: Artifact[] = [
  {
    id: "iron-man-armor-mark-i",
    name: "Iron Man Armor Mark I",
    description: "An object of immense power or significance.",
    firstAppearance: "Unknown",
    properties: [],
    sources: [],
  },
  {
    id: "captain-america-s-shield",
    name: "Captain America's Shield",
    description: "An object of immense power or significance.",
    firstAppearance: "Unknown",
    properties: [],
    sources: [],
  },
  {
    id: "mjolnir",
    name: "Mjolnir",
    description: "An object of immense power or significance.",
    firstAppearance: "Unknown",
    properties: [],
    sources: [],
  },
  {
    id: "stormbreaker",
    name: "Stormbreaker",
    description: "An object of immense power or significance.",
    firstAppearance: "Unknown",
    properties: [],
    sources: [],
  },
  {
    id: "tesseract",
    name: "Tesseract",
    description: "An object of immense power or significance.",
    firstAppearance: "Unknown",
    properties: [],
    sources: [],
  },
  {
    id: "scepter",
    name: "Scepter",
    description: "An object of immense power or significance.",
    firstAppearance: "Unknown",
    properties: [],
    sources: [],
  },
  {
    id: "aether",
    name: "Aether",
    description: "An object of immense power or significance.",
    firstAppearance: "Unknown",
    properties: [],
    sources: [],
  },
  {
    id: "orb",
    name: "Orb",
    description: "An object of immense power or significance.",
    firstAppearance: "Unknown",
    properties: [],
    sources: [],
  },
  {
    id: "eye-of-agamotto",
    name: "Eye of Agamotto",
    description: "An object of immense power or significance.",
    firstAppearance: "Unknown",
    properties: [],
    sources: [],
  },
  {
    id: "infinity-gauntlet",
    name: "Infinity Gauntlet",
    description: "An object of immense power or significance.",
    firstAppearance: "Unknown",
    properties: [],
    sources: [],
  },
  {
    id: "ten-rings",
    name: "Ten Rings",
    description: "An object of immense power or significance.",
    firstAppearance: "Unknown",
    properties: [],
    sources: [],
  },
  {
    id: "darkhold",
    name: "Darkhold",
    description: "An object of immense power or significance.",
    firstAppearance: "Unknown",
    properties: [],
    sources: [],
  },
  {
    id: "quantum-tunnel",
    name: "Quantum Tunnel",
    description: "An object of immense power or significance.",
    firstAppearance: "Unknown",
    properties: [],
    sources: [],
  },
  {
    id: "vibranium",
    name: "Vibranium",
    description: "An object of immense power or significance.",
    firstAppearance: "Unknown",
    properties: [],
    sources: [],
  },
  {
    id: "arc-reactor",
    name: "Arc Reactor",
    description: "An object of immense power or significance.",
    firstAppearance: "Unknown",
    properties: [],
    sources: [],
  },
  {
    id: "yaka-arrow",
    name: "Yaka Arrow",
    description: "An object of immense power or significance.",
    firstAppearance: "Unknown",
    properties: [],
    sources: [],
  },
];
