import { Character } from "../lib/content/schemas";

export const characters: Character[] = [
  {
    id: "tony-stark",
    name: "Tony Stark",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "steve-rogers",
    name: "Steve Rogers",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "thor-odinson",
    name: "Thor Odinson",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "bruce-banner",
    name: "Bruce Banner",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "natasha-romanoff",
    name: "Natasha Romanoff",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "clint-barton",
    name: "Clint Barton",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "james-rhodes",
    name: "James Rhodes",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "sam-wilson",
    name: "Sam Wilson",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "bucky-barnes",
    name: "Bucky Barnes",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "wanda-maximoff",
    name: "Wanda Maximoff",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "vision",
    name: "Vision",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "pietro-maximoff",
    name: "Pietro Maximoff",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "nick-fury",
    name: "Nick Fury",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "maria-hill",
    name: "Maria Hill",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "phil-coulson",
    name: "Phil Coulson",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "peggy-carter",
    name: "Peggy Carter",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "sharon-carter",
    name: "Sharon Carter",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "scott-lang",
    name: "Scott Lang",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "hope-van-dyne",
    name: "Hope van Dyne",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "hank-pym",
    name: "Hank Pym",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "janet-van-dyne",
    name: "Janet van Dyne",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "t-challa",
    name: "T'Challa",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "shuri",
    name: "Shuri",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "okoye",
    name: "Okoye",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "nakia",
    name: "Nakia",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "stephen-strange",
    name: "Stephen Strange",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "wong",
    name: "Wong",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "peter-parker",
    name: "Peter Parker",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "carol-danvers",
    name: "Carol Danvers",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "kamala-khan",
    name: "Kamala Khan",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "monica-rambeau",
    name: "Monica Rambeau",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "peter-quill",
    name: "Peter Quill",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "gamora",
    name: "Gamora",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "drax",
    name: "Drax",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "rocket",
    name: "Rocket",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "groot",
    name: "Groot",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "nebula",
    name: "Nebula",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "mantis",
    name: "Mantis",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "loki",
    name: "Loki",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "sylvie",
    name: "Sylvie",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "mobius",
    name: "Mobius",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "marc-spector",
    name: "Marc Spector",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "steven-grant",
    name: "Steven Grant",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "layla-el-faouly",
    name: "Layla El-Faouly",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "matt-murdock",
    name: "Matt Murdock",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "kingpin",
    name: "Kingpin",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "yelena-belova",
    name: "Yelena Belova",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
  {
    id: "kate-bishop",
    name: "Kate Bishop",
    aliases: [],
    spoilerSafeIdentity: "A significant figure in the MCU.",
    readableLifeStory: "Played a key role in the events of the universe.",
    appearanceOrder: [],
    relationships: [],
    sources: [],
  },
];
