import { Event } from "../lib/content/schemas";

export const events: Event[] = [
  {
    id: "tony-stark-kidnapped-in-afghanistan",
    title: "Tony Stark kidnapped in Afghanistan",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "steve-rogers-receives-super-soldier-serum",
    title: "Steve Rogers receives Super Soldier Serum",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "captain-america-frozen-in-ice",
    title: "Captain America frozen in ice",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "captain-marvel-returns-to-earth",
    title: "Captain Marvel returns to Earth",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "tony-stark-declares-i-am-iron-man",
    title: "Tony Stark declares I am Iron Man",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "avengers-initiative-formed",
    title: "Avengers Initiative formed",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "thor-exiled-to-earth",
    title: "Thor exiled to Earth",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "battle-of-new-york",
    title: "Battle of New York",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "fall-of-shield",
    title: "Fall of SHIELD",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "creation-of-ultron",
    title: "Creation of Ultron",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "destruction-of-sokovia",
    title: "Destruction of Sokovia",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "sokovia-accords-signed",
    title: "Sokovia Accords signed",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "avengers-civil-war",
    title: "Avengers Civil War",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "doctor-strange-defeats-dormammu",
    title: "Doctor Strange defeats Dormammu",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "destruction-of-asgard",
    title: "Destruction of Asgard",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "thanos-attacks-the-statesman",
    title: "Thanos attacks the Statesman",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "the-snap",
    title: "The Snap",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "scott-lang-escapes-quantum-realm",
    title: "Scott Lang escapes Quantum Realm",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "the-time-heist",
    title: "The Time Heist",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "the-blip-final-battle",
    title: "The Blip / Final Battle",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "loki-escapes-timeline",
    title: "Loki escapes timeline",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "westview-anomaly",
    title: "Westview Anomaly",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "sam-wilson-becomes-captain-america",
    title: "Sam Wilson becomes Captain America",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "ten-rings-beacon-activated",
    title: "Ten Rings beacon activated",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "memory-spell-breaks-multiverse",
    title: "Memory spell breaks multiverse",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "tiamut-emergence-stopped",
    title: "Tiamut emergence stopped",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "incursions-begin",
    title: "Incursions begin",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "wakanda-vs-talokan",
    title: "Wakanda vs Talokan",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "kang-defeated-in-quantum-realm",
    title: "Kang defeated in Quantum Realm",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "guardians-defeat-high-evolutionary",
    title: "Guardians defeat High Evolutionary",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "marvels-entangle-powers",
    title: "Marvels entangle powers",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "deadpool-enters-void",
    title: "Deadpool enters Void",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "new-avengers-formed",
    title: "New Avengers formed",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "fantastic-four-arrive",
    title: "Fantastic Four arrive",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "doctor-doom-appears",
    title: "Doctor Doom appears",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "secret-wars-begin",
    title: "Secret Wars begin",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "event-37",
    title: "Event 37",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "event-38",
    title: "Event 38",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "event-39",
    title: "Event 39",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
  {
    id: "event-40",
    title: "Event 40",
    shortSpoilerFreeSummary: "A major turning point.",
    fullSpoilerSummary: "Significant consequences rippled through the timeline.",
    inUniverseDateRange: "Unknown",
    universe: "Earth-616",
    participants: [],
    relatedFilms: [],
    causes: [],
    consequences: [],
    artifacts: [],
    sourceLinks: [],
    confidenceLevel: "High" as const,
  },
];
