import { Faction } from "../lib/content/schemas";

export const factions: Faction[] = [
  {
    id: "avengers",
    name: "Avengers",
    description: "A group operating within the MCU.",
    purpose: "Various organizational goals.",
    leaderIds: [],
    memberIds: [],
    sources: [],
  },
  {
    id: "s-h-i-e-l-d-",
    name: "S.H.I.E.L.D.",
    description: "A group operating within the MCU.",
    purpose: "Various organizational goals.",
    leaderIds: [],
    memberIds: [],
    sources: [],
  },
  {
    id: "hydra",
    name: "HYDRA",
    description: "A group operating within the MCU.",
    purpose: "Various organizational goals.",
    leaderIds: [],
    memberIds: [],
    sources: [],
  },
  {
    id: "guardians-of-the-galaxy",
    name: "Guardians of the Galaxy",
    description: "A group operating within the MCU.",
    purpose: "Various organizational goals.",
    leaderIds: [],
    memberIds: [],
    sources: [],
  },
  {
    id: "dora-milaje",
    name: "Dora Milaje",
    description: "A group operating within the MCU.",
    purpose: "Various organizational goals.",
    leaderIds: [],
    memberIds: [],
    sources: [],
  },
  {
    id: "masters-of-the-mystic-arts",
    name: "Masters of the Mystic Arts",
    description: "A group operating within the MCU.",
    purpose: "Various organizational goals.",
    leaderIds: [],
    memberIds: [],
    sources: [],
  },
  {
    id: "tva",
    name: "TVA",
    description: "A group operating within the MCU.",
    purpose: "Various organizational goals.",
    leaderIds: [],
    memberIds: [],
    sources: [],
  },
  {
    id: "ten-rings",
    name: "Ten Rings",
    description: "A group operating within the MCU.",
    purpose: "Various organizational goals.",
    leaderIds: [],
    memberIds: [],
    sources: [],
  },
  {
    id: "red-room",
    name: "Red Room",
    description: "A group operating within the MCU.",
    purpose: "Various organizational goals.",
    leaderIds: [],
    memberIds: [],
    sources: [],
  },
  {
    id: "eternals",
    name: "Eternals",
    description: "A group operating within the MCU.",
    purpose: "Various organizational goals.",
    leaderIds: [],
    memberIds: [],
    sources: [],
  },
  {
    id: "deviants",
    name: "Deviants",
    description: "A group operating within the MCU.",
    purpose: "Various organizational goals.",
    leaderIds: [],
    memberIds: [],
    sources: [],
  },
  {
    id: "nova-corps",
    name: "Nova Corps",
    description: "A group operating within the MCU.",
    purpose: "Various organizational goals.",
    leaderIds: [],
    memberIds: [],
    sources: [],
  },
  {
    id: "ravagers",
    name: "Ravagers",
    description: "A group operating within the MCU.",
    purpose: "Various organizational goals.",
    leaderIds: [],
    memberIds: [],
    sources: [],
  },
  {
    id: "flag-smashers",
    name: "Flag Smashers",
    description: "A group operating within the MCU.",
    purpose: "Various organizational goals.",
    leaderIds: [],
    memberIds: [],
    sources: [],
  },
  {
    id: "illuminati",
    name: "Illuminati",
    description: "A group operating within the MCU.",
    purpose: "Various organizational goals.",
    leaderIds: [],
    memberIds: [],
    sources: [],
  },
  {
    id: "x-men",
    name: "X-Men",
    description: "A group operating within the MCU.",
    purpose: "Various organizational goals.",
    leaderIds: [],
    memberIds: [],
    sources: [],
  },
];
