import { Film } from "../lib/content/schemas";

export const films: Film[] = [
  // PHASE ONE
  { id: "iron-man", title: "Iron Man", releaseYear: 2008, releaseOrder: 1, chronologicalOrder: 3, phase: 1, spoilerSafePremise: "Tony Stark builds an armored suit to escape captivity.", whyItMattersSafe: "Establishes Tony Stark and the MCU.", watchNextIds: ["incredible-hulk"], prerequisiteIds: [], sources: [] },
  { id: "incredible-hulk", title: "The Incredible Hulk", releaseYear: 2008, releaseOrder: 2, chronologicalOrder: 4, phase: 1, spoilerSafePremise: "Bruce Banner seeks a cure for his gamma radiation.", whyItMattersSafe: "Introduces the Hulk.", watchNextIds: ["iron-man-2"], prerequisiteIds: ["iron-man"], sources: [] },
  { id: "iron-man-2", title: "Iron Man 2", releaseYear: 2010, releaseOrder: 3, chronologicalOrder: 5, phase: 1, spoilerSafePremise: "Tony Stark faces enemies and his own mortality.", whyItMattersSafe: "Introduces Black Widow and War Machine.", watchNextIds: ["thor"], prerequisiteIds: ["iron-man"], sources: [] },
  { id: "thor", title: "Thor", releaseYear: 2011, releaseOrder: 4, chronologicalOrder: 6, phase: 1, spoilerSafePremise: "The arrogant god Thor is banished to Earth.", whyItMattersSafe: "Introduces Thor, Loki, and Asgard.", watchNextIds: ["captain-america-first-avenger"], prerequisiteIds: [], sources: [] },
  { id: "captain-america-first-avenger", title: "Captain America: The First Avenger", releaseYear: 2011, releaseOrder: 5, chronologicalOrder: 1, phase: 1, spoilerSafePremise: "Steve Rogers becomes Captain America during WWII.", whyItMattersSafe: "Origin of Captain America and the Tesseract.", watchNextIds: ["the-avengers"], prerequisiteIds: [], sources: [] },
  { id: "the-avengers", title: "The Avengers", releaseYear: 2012, releaseOrder: 6, chronologicalOrder: 7, phase: 1, spoilerSafePremise: "Earth's mightiest heroes must come together.", whyItMattersSafe: "The culmination of Phase 1.", watchNextIds: ["iron-man-3"], prerequisiteIds: ["iron-man", "thor", "captain-america-first-avenger"], sources: [] },

  // PHASE TWO
  { id: "iron-man-3", title: "Iron Man 3", releaseYear: 2013, releaseOrder: 7, chronologicalOrder: 8, phase: 2, spoilerSafePremise: "Tony Stark struggles with the aftermath of New York.", whyItMattersSafe: "Explores Tony's trauma.", watchNextIds: ["thor-dark-world"], prerequisiteIds: ["the-avengers"], sources: [] },
  { id: "thor-dark-world", title: "Thor: The Dark World", releaseYear: 2013, releaseOrder: 8, chronologicalOrder: 9, phase: 2, spoilerSafePremise: "Thor must save Earth and all the Nine Realms.", whyItMattersSafe: "Introduces the Reality Stone.", watchNextIds: ["captain-america-winter-soldier"], prerequisiteIds: ["thor", "the-avengers"], sources: [] },
  { id: "captain-america-winter-soldier", title: "Captain America: The Winter Soldier", releaseYear: 2014, releaseOrder: 9, chronologicalOrder: 10, phase: 2, spoilerSafePremise: "Steve Rogers uncovers a conspiracy within S.H.I.E.L.D.", whyItMattersSafe: "Changes the landscape of the MCU entirely.", watchNextIds: ["guardians-of-the-galaxy"], prerequisiteIds: ["captain-america-first-avenger", "the-avengers"], sources: [] },
  { id: "guardians-of-the-galaxy", title: "Guardians of the Galaxy", releaseYear: 2014, releaseOrder: 10, chronologicalOrder: 11, phase: 2, spoilerSafePremise: "A group of intergalactic criminals must pull together.", whyItMattersSafe: "Introduces the cosmic side of the MCU.", watchNextIds: ["avengers-age-of-ultron"], prerequisiteIds: [], sources: [] },
  { id: "avengers-age-of-ultron", title: "Avengers: Age of Ultron", releaseYear: 2015, releaseOrder: 11, chronologicalOrder: 13, phase: 2, spoilerSafePremise: "The Avengers must stop a rogue artificial intelligence.", whyItMattersSafe: "Introduces Vision and Wanda.", watchNextIds: ["ant-man"], prerequisiteIds: ["the-avengers"], sources: [] },
  { id: "ant-man", title: "Ant-Man", releaseYear: 2015, releaseOrder: 12, chronologicalOrder: 14, phase: 2, spoilerSafePremise: "A thief must embrace his inner hero and help his mentor.", whyItMattersSafe: "Introduces Ant-Man and the Quantum Realm concept.", watchNextIds: ["captain-america-civil-war"], prerequisiteIds: [], sources: [] },

  // PHASE THREE
  { id: "captain-america-civil-war", title: "Captain America: Civil War", releaseYear: 2016, releaseOrder: 13, chronologicalOrder: 16, phase: 3, spoilerSafePremise: "Political interference causes a rift between former allies.", whyItMattersSafe: "Fractures the Avengers.", watchNextIds: ["doctor-strange"], prerequisiteIds: ["avengers-age-of-ultron", "captain-america-winter-soldier"], sources: [] },
  { id: "doctor-strange", title: "Doctor Strange", releaseYear: 2016, releaseOrder: 14, chronologicalOrder: 17, phase: 3, spoilerSafePremise: "A brilliant surgeon discovers the hidden world of magic.", whyItMattersSafe: "Introduces magic and the Time Stone.", watchNextIds: ["guardians-of-the-galaxy-vol-2"], prerequisiteIds: [], sources: [] },
  { id: "guardians-of-the-galaxy-vol-2", title: "Guardians of the Galaxy Vol. 2", releaseYear: 2017, releaseOrder: 15, chronologicalOrder: 12, phase: 3, spoilerSafePremise: "The Guardians must fight to keep their newfound family together.", whyItMattersSafe: "Expands the cosmic lore.", watchNextIds: ["spider-man-homecoming"], prerequisiteIds: ["guardians-of-the-galaxy"], sources: [] },
  { id: "spider-man-homecoming", title: "Spider-Man: Homecoming", releaseYear: 2017, releaseOrder: 16, chronologicalOrder: 18, phase: 3, spoilerSafePremise: "Peter Parker navigates high school and being a superhero.", whyItMattersSafe: "Brings Spider-Man into the MCU.", watchNextIds: ["thor-ragnarok"], prerequisiteIds: ["captain-america-civil-war"], sources: [] },
  { id: "thor-ragnarok", title: "Thor: Ragnarok", releaseYear: 2017, releaseOrder: 17, chronologicalOrder: 19, phase: 3, spoilerSafePremise: "Thor is imprisoned and must race to save Asgard.", whyItMattersSafe: "Redefines Thor and sets up Infinity War.", watchNextIds: ["black-panther"], prerequisiteIds: ["thor-dark-world"], sources: [] },
  { id: "black-panther", title: "Black Panther", releaseYear: 2018, releaseOrder: 18, chronologicalOrder: 20, phase: 3, spoilerSafePremise: "T'Challa returns home to take his rightful place as king.", whyItMattersSafe: "Introduces Wakanda.", watchNextIds: ["avengers-infinity-war"], prerequisiteIds: ["captain-america-civil-war"], sources: [] },
  { id: "avengers-infinity-war", title: "Avengers: Infinity War", releaseYear: 2018, releaseOrder: 19, chronologicalOrder: 21, phase: 3, spoilerSafePremise: "The Avengers and their allies must be willing to sacrifice all.", whyItMattersSafe: "The beginning of the culmination.", watchNextIds: ["ant-man-and-the-wasp"], prerequisiteIds: ["captain-america-civil-war", "thor-ragnarok"], sources: [] },
  { id: "ant-man-and-the-wasp", title: "Ant-Man and the Wasp", releaseYear: 2018, releaseOrder: 20, chronologicalOrder: 22, phase: 3, spoilerSafePremise: "Scott Lang balances being a hero and a father.", whyItMattersSafe: "Expands on the Quantum Realm.", watchNextIds: ["captain-marvel"], prerequisiteIds: ["ant-man", "captain-america-civil-war"], sources: [] },
  { id: "captain-marvel", title: "Captain Marvel", releaseYear: 2019, releaseOrder: 21, chronologicalOrder: 2, phase: 3, spoilerSafePremise: "Carol Danvers becomes one of the universe's most powerful heroes.", whyItMattersSafe: "Origin of Captain Marvel and the Tesseract's history.", watchNextIds: ["avengers-endgame"], prerequisiteIds: [], sources: [] },
  { id: "avengers-endgame", title: "Avengers: Endgame", releaseYear: 2019, releaseOrder: 22, chronologicalOrder: 23, phase: 3, spoilerSafePremise: "The remaining Avengers take one final stand.", whyItMattersSafe: "The epic conclusion to the Infinity Saga.", watchNextIds: ["spider-man-far-from-home"], prerequisiteIds: ["avengers-infinity-war", "ant-man-and-the-wasp", "captain-marvel"], sources: [] },
  { id: "spider-man-far-from-home", title: "Spider-Man: Far From Home", releaseYear: 2019, releaseOrder: 23, chronologicalOrder: 24, phase: 3, spoilerSafePremise: "Peter Parker goes on a school trip to Europe.", whyItMattersSafe: "The epilogue to the Infinity Saga.", watchNextIds: ["black-widow"], prerequisiteIds: ["avengers-endgame"], sources: [] },

  // PHASE FOUR
  { id: "black-widow", title: "Black Widow", releaseYear: 2021, releaseOrder: 24, chronologicalOrder: 15, phase: 4, spoilerSafePremise: "Natasha Romanoff confronts the darker parts of her ledger.", whyItMattersSafe: "Fills the gap between Civil War and Infinity War.", watchNextIds: ["shang-chi"], prerequisiteIds: ["captain-america-civil-war"], sources: [] },
  { id: "shang-chi", title: "Shang-Chi and the Legend of the Ten Rings", releaseYear: 2021, releaseOrder: 25, chronologicalOrder: 26, phase: 4, spoilerSafePremise: "Shang-Chi must confront the past he thought he left behind.", whyItMattersSafe: "Introduces Shang-Chi and the Ten Rings.", watchNextIds: ["eternals"], prerequisiteIds: [], sources: [] },
  { id: "eternals", title: "Eternals", releaseYear: 2021, releaseOrder: 26, chronologicalOrder: 25, phase: 4, spoilerSafePremise: "Immortal beings emerge from hiding to protect Earth.", whyItMattersSafe: "Expands MCU cosmology.", watchNextIds: ["spider-man-no-way-home"], prerequisiteIds: [], sources: [] },
  { id: "spider-man-no-way-home", title: "Spider-Man: No Way Home", releaseYear: 2021, releaseOrder: 27, chronologicalOrder: 27, phase: 4, spoilerSafePremise: "Peter Parker's secret identity is revealed.", whyItMattersSafe: "Opens the Multiverse.", watchNextIds: ["doctor-strange-in-the-multiverse-of-madness"], prerequisiteIds: ["spider-man-far-from-home"], sources: [] },
  { id: "doctor-strange-in-the-multiverse-of-madness", title: "Doctor Strange in the Multiverse of Madness", releaseYear: 2022, releaseOrder: 28, chronologicalOrder: 28, phase: 4, spoilerSafePremise: "Doctor Strange traverses the mind-bending realities of the Multiverse.", whyItMattersSafe: "Explores the consequences of Multiversal travel.", watchNextIds: ["thor-love-and-thunder"], prerequisiteIds: ["doctor-strange", "spider-man-no-way-home"], sources: [] },
  { id: "thor-love-and-thunder", title: "Thor: Love and Thunder", releaseYear: 2022, releaseOrder: 29, chronologicalOrder: 29, phase: 4, spoilerSafePremise: "Thor enlists the help of Valkyrie, Korg and ex-girlfriend Jane Foster.", whyItMattersSafe: "Thor's journey of self-discovery.", watchNextIds: ["black-panther-wakanda-forever"], prerequisiteIds: ["thor-ragnarok", "avengers-endgame"], sources: [] },
  { id: "black-panther-wakanda-forever", title: "Black Panther: Wakanda Forever", releaseYear: 2022, releaseOrder: 30, chronologicalOrder: 30, phase: 4, spoilerSafePremise: "The leaders of Wakanda fight to protect their nation.", whyItMattersSafe: "Passes the mantle of Black Panther.", watchNextIds: ["ant-man-and-the-wasp-quantumania"], prerequisiteIds: ["black-panther", "avengers-endgame"], sources: [] },

  // PHASE FIVE
  { id: "ant-man-and-the-wasp-quantumania", title: "Ant-Man and the Wasp: Quantumania", releaseYear: 2023, releaseOrder: 31, chronologicalOrder: 31, phase: 5, spoilerSafePremise: "Scott Lang and Hope Van Dyne explore the Quantum Realm.", whyItMattersSafe: "Introduces Kang the Conqueror.", watchNextIds: ["guardians-of-the-galaxy-vol-3"], prerequisiteIds: ["ant-man-and-the-wasp", "avengers-endgame"], sources: [] },
  { id: "guardians-of-the-galaxy-vol-3", title: "Guardians of the Galaxy Vol. 3", releaseYear: 2023, releaseOrder: 32, chronologicalOrder: 32, phase: 5, spoilerSafePremise: "The Guardians rally to defend the universe and protect one of their own.", whyItMattersSafe: "The conclusion of the Guardians' story.", watchNextIds: ["the-marvels"], prerequisiteIds: ["guardians-of-the-galaxy-vol-2", "avengers-endgame"], sources: [] },
  { id: "the-marvels", title: "The Marvels", releaseYear: 2023, releaseOrder: 33, chronologicalOrder: 33, phase: 5, spoilerSafePremise: "Carol Danvers, Kamala Khan, and Monica Rambeau's powers become entangled.", whyItMattersSafe: "Expands the cosmic universe.", watchNextIds: ["deadpool-and-wolverine"], prerequisiteIds: ["captain-marvel"], sources: [] },
  { id: "deadpool-and-wolverine", title: "Deadpool & Wolverine", releaseYear: 2024, releaseOrder: 34, chronologicalOrder: 34, phase: 5, spoilerSafePremise: "Deadpool and Wolverine team up.", whyItMattersSafe: "Brings mutants into the MCU.", watchNextIds: ["captain-america-brave-new-world"], prerequisiteIds: [], sources: [] },
  { id: "captain-america-brave-new-world", title: "Captain America: Brave New World", releaseYear: 2025, releaseOrder: 35, chronologicalOrder: 35, phase: 5, spoilerSafePremise: "Sam Wilson takes on the mantle of Captain America.", whyItMattersSafe: "Continues the Captain America legacy.", watchNextIds: ["thunderbolts"], prerequisiteIds: ["avengers-endgame"], sources: [] },
  { id: "thunderbolts", title: "Thunderbolts*", releaseYear: 2025, releaseOrder: 36, chronologicalOrder: 36, phase: 5, spoilerSafePremise: "A group of antiheroes goes on missions for the government.", whyItMattersSafe: "Introduces a new team dynamic.", watchNextIds: [], prerequisiteIds: ["black-widow"], sources: [] },

  // PHASE SIX
  { id: "fantastic-four-first-steps", title: "The Fantastic Four: First Steps", releaseYear: 2025, releaseOrder: 37, chronologicalOrder: null, phase: 6, spoilerSafePremise: "The Fantastic Four's retro-futurist alternate universe.", whyItMattersSafe: "Introduces Marvel's First Family.", watchNextIds: ["spider-man-brand-new-day"], prerequisiteIds: [], sources: [] },
  { id: "spider-man-brand-new-day", title: "Spider-Man 4 (TBD)", releaseYear: 2026, releaseOrder: 38, chronologicalOrder: 37, phase: 6, spoilerSafePremise: "Peter Parker's new street-level life.", whyItMattersSafe: "Spider-Man's post-No Way Home era.", watchNextIds: ["avengers-doomsday"], prerequisiteIds: ["spider-man-no-way-home"], sources: [] },
  { id: "avengers-doomsday", title: "Avengers: Doomsday", releaseYear: 2026, releaseOrder: 39, chronologicalOrder: 38, phase: 6, spoilerSafePremise: "Doctor Doom threatens the multiverse.", whyItMattersSafe: "The next Avengers crossover.", watchNextIds: ["avengers-secret-wars"], prerequisiteIds: ["fantastic-four-first-steps", "doctor-strange-in-the-multiverse-of-madness"], sources: [] },
  { id: "avengers-secret-wars", title: "Avengers: Secret Wars", releaseYear: 2027, releaseOrder: 40, chronologicalOrder: 39, phase: 6, spoilerSafePremise: "The climax of the Multiverse Saga.", whyItMattersSafe: "The culmination of phases 4-6.", watchNextIds: [], prerequisiteIds: ["avengers-doomsday"], sources: [] },
  { id: "blade", title: "Blade", releaseYear: 2027, releaseOrder: 41, chronologicalOrder: null, phase: 6, spoilerSafePremise: "TBD", whyItMattersSafe: "TBD", watchNextIds: [], prerequisiteIds: [], sources: [] }
];
