import { Film } from "../lib/content/schemas";

export const films: Film[] = [
  // PHASE ONE
  { id: "iron-man", title: "Iron Man", releaseYear: 2008, phase: 1, spoilerSafePremise: "Tony Stark builds an armored suit to escape captivity.", whyItMatters: "Establishes Tony Stark and the MCU.", watchNextIds: ["incredible-hulk"], prerequisiteIds: [], sources: [] },
  { id: "incredible-hulk", title: "The Incredible Hulk", releaseYear: 2008, phase: 1, spoilerSafePremise: "Bruce Banner seeks a cure for his gamma radiation.", whyItMatters: "Introduces the Hulk.", watchNextIds: ["iron-man-2"], prerequisiteIds: ["iron-man"], sources: [] },
  { id: "iron-man-2", title: "Iron Man 2", releaseYear: 2010, phase: 1, spoilerSafePremise: "Tony Stark faces enemies and his own mortality.", whyItMatters: "Introduces Black Widow and War Machine.", watchNextIds: ["thor"], prerequisiteIds: ["iron-man"], sources: [] },
  { id: "thor", title: "Thor", releaseYear: 2011, phase: 1, spoilerSafePremise: "The arrogant god Thor is banished to Earth.", whyItMatters: "Introduces Thor, Loki, and Asgard.", watchNextIds: ["captain-america-first-avenger"], prerequisiteIds: [], sources: [] },
  { id: "captain-america-first-avenger", title: "Captain America: The First Avenger", releaseYear: 2011, phase: 1, spoilerSafePremise: "Steve Rogers becomes Captain America during WWII.", whyItMatters: "Origin of Captain America and the Tesseract.", watchNextIds: ["the-avengers"], prerequisiteIds: [], sources: [] },
  { id: "the-avengers", title: "The Avengers", releaseYear: 2012, phase: 1, spoilerSafePremise: "Earth's mightiest heroes must come together.", whyItMatters: "The culmination of Phase 1.", watchNextIds: ["iron-man-3"], prerequisiteIds: ["iron-man", "thor", "captain-america-first-avenger"], sources: [] },

  // PHASE TWO
  { id: "iron-man-3", title: "Iron Man 3", releaseYear: 2013, phase: 2, spoilerSafePremise: "Tony Stark struggles with the aftermath of New York.", whyItMatters: "Explores Tony's trauma.", watchNextIds: ["thor-dark-world"], prerequisiteIds: ["the-avengers"], sources: [] },
  { id: "thor-dark-world", title: "Thor: The Dark World", releaseYear: 2013, phase: 2, spoilerSafePremise: "Thor must save Earth and all the Nine Realms.", whyItMatters: "Introduces the Reality Stone.", watchNextIds: ["captain-america-winter-soldier"], prerequisiteIds: ["thor", "the-avengers"], sources: [] },
  { id: "captain-america-winter-soldier", title: "Captain America: The Winter Soldier", releaseYear: 2014, phase: 2, spoilerSafePremise: "Steve Rogers uncovers a conspiracy within S.H.I.E.L.D.", whyItMatters: "Changes the landscape of the MCU entirely.", watchNextIds: ["guardians-of-the-galaxy"], prerequisiteIds: ["captain-america-first-avenger", "the-avengers"], sources: [] },
  { id: "guardians-of-the-galaxy", title: "Guardians of the Galaxy", releaseYear: 2014, phase: 2, spoilerSafePremise: "A group of intergalactic criminals must pull together.", whyItMatters: "Introduces the cosmic side of the MCU.", watchNextIds: ["avengers-age-of-ultron"], prerequisiteIds: [], sources: [] },
  { id: "avengers-age-of-ultron", title: "Avengers: Age of Ultron", releaseYear: 2015, phase: 2, spoilerSafePremise: "The Avengers must stop a rogue artificial intelligence.", whyItMatters: "Introduces Vision and Wanda.", watchNextIds: ["ant-man"], prerequisiteIds: ["the-avengers"], sources: [] },
  { id: "ant-man", title: "Ant-Man", releaseYear: 2015, phase: 2, spoilerSafePremise: "A thief must embrace his inner hero and help his mentor.", whyItMatters: "Introduces Ant-Man and the Quantum Realm concept.", watchNextIds: ["captain-america-civil-war"], prerequisiteIds: [], sources: [] },

  // PHASE THREE
  { id: "captain-america-civil-war", title: "Captain America: Civil War", releaseYear: 2016, phase: 3, spoilerSafePremise: "Political interference causes a rift between former allies.", whyItMatters: "Fractures the Avengers.", watchNextIds: ["doctor-strange"], prerequisiteIds: ["avengers-age-of-ultron", "captain-america-winter-soldier"], sources: [] },
  { id: "doctor-strange", title: "Doctor Strange", releaseYear: 2016, phase: 3, spoilerSafePremise: "A neurosurgeon discovers the hidden world of magic.", whyItMatters: "Introduces the mystic arts and the Time Stone.", watchNextIds: ["guardians-vol-2"], prerequisiteIds: [], sources: [] },
  { id: "guardians-vol-2", title: "Guardians of the Galaxy Vol. 2", releaseYear: 2017, phase: 3, spoilerSafePremise: "The Guardians struggle to keep their newfound family together.", whyItMatters: "Expands the cosmic lore.", watchNextIds: ["spider-man-homecoming"], prerequisiteIds: ["guardians-of-the-galaxy"], sources: [] },
  { id: "spider-man-homecoming", title: "Spider-Man: Homecoming", releaseYear: 2017, phase: 3, spoilerSafePremise: "Peter Parker tries to balance high school and being a hero.", whyItMatters: "Integrates Spider-Man into the MCU.", watchNextIds: ["thor-ragnarok"], prerequisiteIds: ["captain-america-civil-war"], sources: [] },
  { id: "thor-ragnarok", title: "Thor: Ragnarok", releaseYear: 2017, phase: 3, spoilerSafePremise: "Thor must escape an alien planet and save Asgard.", whyItMatters: "Reinvents Thor's character arc.", watchNextIds: ["black-panther"], prerequisiteIds: ["avengers-age-of-ultron", "thor-dark-world"], sources: [] },
  { id: "black-panther", title: "Black Panther", releaseYear: 2018, phase: 3, spoilerSafePremise: "T'Challa returns home to Wakanda to take his rightful place as king.", whyItMatters: "Explores Wakanda and its legacy.", watchNextIds: ["avengers-infinity-war"], prerequisiteIds: ["captain-america-civil-war"], sources: [] },
  { id: "avengers-infinity-war", title: "Avengers: Infinity War", releaseYear: 2018, phase: 3, spoilerSafePremise: "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat Thanos.", whyItMatters: "The culmination of everything prior.", watchNextIds: ["ant-man-and-the-wasp"], prerequisiteIds: ["captain-america-civil-war", "thor-ragnarok", "guardians-of-the-galaxy"], sources: [] },
  { id: "ant-man-and-the-wasp", title: "Ant-Man and the Wasp", releaseYear: 2018, phase: 3, spoilerSafePremise: "Scott Lang balances being a hero and a father.", whyItMatters: "Explores the Quantum Realm.", watchNextIds: ["captain-marvel"], prerequisiteIds: ["ant-man", "captain-america-civil-war"], sources: [] },
  { id: "captain-marvel", title: "Captain Marvel", releaseYear: 2019, phase: 3, spoilerSafePremise: "Carol Danvers becomes one of the universe's most powerful heroes.", whyItMatters: "Origin of Captain Marvel and the Avengers Initiative name.", watchNextIds: ["avengers-endgame"], prerequisiteIds: [], sources: [] },
  { id: "avengers-endgame", title: "Avengers: Endgame", releaseYear: 2019, phase: 3, spoilerSafePremise: "The remaining Avengers take one final stand.", whyItMatters: "The conclusion to the Infinity Saga.", watchNextIds: ["spider-man-far-from-home"], prerequisiteIds: ["avengers-infinity-war", "ant-man-and-the-wasp", "captain-marvel"], sources: [] },
  { id: "spider-man-far-from-home", title: "Spider-Man: Far From Home", releaseYear: 2019, phase: 3, spoilerSafePremise: "Peter Parker faces new threats on a school trip.", whyItMatters: "The epilogue of the Infinity Saga.", watchNextIds: ["black-widow"], prerequisiteIds: ["avengers-endgame", "spider-man-homecoming"], sources: [] },

  // PHASE FOUR
  { id: "black-widow", title: "Black Widow", releaseYear: 2021, phase: 4, spoilerSafePremise: "Natasha Romanoff confronts the darker parts of her ledger.", whyItMatters: "Explores Natasha's past.", watchNextIds: ["shang-chi"], prerequisiteIds: ["captain-america-civil-war"], sources: [] },
  { id: "shang-chi", title: "Shang-Chi and the Legend of the Ten Rings", releaseYear: 2021, phase: 4, spoilerSafePremise: "Shang-Chi must confront the past he thought he left behind.", whyItMatters: "Introduces Shang-Chi and the true Ten Rings.", watchNextIds: ["eternals"], prerequisiteIds: [], sources: [] },
  { id: "eternals", title: "Eternals", releaseYear: 2021, phase: 4, spoilerSafePremise: "Ancient aliens must reunite to defend Earth.", whyItMatters: "Expands the cosmic and historical scope of the MCU.", watchNextIds: ["spider-man-no-way-home"], prerequisiteIds: ["avengers-endgame"], sources: [] },
  { id: "spider-man-no-way-home", title: "Spider-Man: No Way Home", releaseYear: 2021, phase: 4, spoilerSafePremise: "Peter Parker asks Doctor Strange for help, causing a multiversal crisis.", whyItMatters: "Major multiversal consequences.", watchNextIds: ["doctor-strange-multiverse"], prerequisiteIds: ["spider-man-far-from-home"], sources: [] },
  { id: "doctor-strange-multiverse", title: "Doctor Strange in the Multiverse of Madness", releaseYear: 2022, phase: 4, spoilerSafePremise: "Doctor Strange traverses mind-bending realities.", whyItMatters: "Deepens the rules of the Multiverse.", watchNextIds: ["thor-love-and-thunder"], prerequisiteIds: ["spider-man-no-way-home"], sources: [] },
  { id: "thor-love-and-thunder", title: "Thor: Love and Thunder", releaseYear: 2022, phase: 4, spoilerSafePremise: "Thor enlists help to combat Gorr the God Butcher.", whyItMatters: "Continues Thor's post-Endgame journey.", watchNextIds: ["black-panther-wakanda-forever"], prerequisiteIds: ["avengers-endgame"], sources: [] },
  { id: "black-panther-wakanda-forever", title: "Black Panther: Wakanda Forever", releaseYear: 2022, phase: 4, spoilerSafePremise: "Wakanda fights to protect their nation from intervening world powers.", whyItMatters: "Honors T'Challa's legacy and introduces Namor.", watchNextIds: ["ant-man-quantumania"], prerequisiteIds: ["black-panther", "avengers-endgame"], sources: [] },

  // PHASE FIVE
  { id: "ant-man-quantumania", title: "Ant-Man and the Wasp: Quantumania", releaseYear: 2023, phase: 5, spoilerSafePremise: "Scott Lang and Hope Van Dyne explore the Quantum Realm.", whyItMatters: "Introduces Kang the Conqueror on the big screen.", watchNextIds: ["guardians-vol-3"], prerequisiteIds: ["ant-man-and-the-wasp", "avengers-endgame"], sources: [] },
  { id: "guardians-vol-3", title: "Guardians of the Galaxy Vol. 3", releaseYear: 2023, phase: 5, spoilerSafePremise: "The Guardians must save one of their own.", whyItMatters: "Concludes the story of the original Guardians team.", watchNextIds: ["the-marvels"], prerequisiteIds: ["avengers-endgame", "guardians-vol-2"], sources: [] },
  { id: "the-marvels", title: "The Marvels", releaseYear: 2023, phase: 5, spoilerSafePremise: "Carol, Monica, and Kamala's powers become entangled.", whyItMatters: "Unites the three heroes and teases future multiversal threats.", watchNextIds: ["deadpool-wolverine"], prerequisiteIds: ["captain-marvel"], sources: [] },
  { id: "deadpool-wolverine", title: "Deadpool & Wolverine", releaseYear: 2024, phase: 5, spoilerSafePremise: "Deadpool's TVA-related journey integrates alternate-universe characters.", whyItMatters: "Introduces mutants more fully into the MCU.", watchNextIds: ["captain-america-brave-new-world"], prerequisiteIds: ["doctor-strange-multiverse"], sources: [] },
  { id: "captain-america-brave-new-world", title: "Captain America: Brave New World", releaseYear: 2025, phase: 5, spoilerSafePremise: "Sam Wilson's first feature-film era as Captain America.", whyItMatters: "Establishes the new geopolitical landscape.", watchNextIds: ["thunderbolts"], prerequisiteIds: [], sources: [] },
  { id: "thunderbolts", title: "Thunderbolts* / The New Avengers", releaseYear: 2025, phase: 5, spoilerSafePremise: "Valentina's antihero program takes shape.", whyItMatters: "Emergence of the New Avengers.", watchNextIds: ["fantastic-four-first-steps"], prerequisiteIds: ["black-widow"], sources: [] },

  // PHASE SIX
  { id: "fantastic-four-first-steps", title: "The Fantastic Four: First Steps", releaseYear: 2025, phase: 6, spoilerSafePremise: "The Fantastic Four's retro-futurist alternate universe.", whyItMatters: "Introduces Marvel's First Family.", watchNextIds: ["spider-man-brand-new-day"], prerequisiteIds: [], sources: [] },
  
  // UPCOMING
  { id: "spider-man-brand-new-day", title: "Spider-Man: Brand New Day", releaseYear: 2026, phase: 6, spoilerSafePremise: "Upcoming entry in the Spider-Man series.", whyItMatters: "Follows the events of No Way Home.", watchNextIds: ["avengers-doomsday"], prerequisiteIds: ["spider-man-no-way-home"], sources: [] },
  { id: "avengers-doomsday", title: "Avengers: Doomsday", releaseYear: 2026, phase: 6, spoilerSafePremise: "The universe faces Doctor Doom.", whyItMatters: "The first part of the Multiverse Saga's climax.", watchNextIds: ["avengers-secret-wars"], prerequisiteIds: ["fantastic-four-first-steps"], sources: [] },
  { id: "avengers-secret-wars", title: "Avengers: Secret Wars", releaseYear: 2027, phase: 6, spoilerSafePremise: "The ultimate multiversal conflict.", whyItMatters: "The culmination of the Multiverse Saga.", watchNextIds: ["blade"], prerequisiteIds: ["avengers-doomsday"], sources: [] },
  { id: "blade", title: "Blade", releaseYear: 2027, phase: null, spoilerSafePremise: "TBD", whyItMatters: "TBD", watchNextIds: [], prerequisiteIds: [], sources: [] },
];
