import { Location } from "../lib/content/schemas";

export const locations: Location[] = [
  {
    id: "stark-tower-avengers-tower",
    name: "Stark Tower / Avengers Tower",
    description: "A significant place.",
    planet: "Unknown",
    universe: "Earth-616",
    significance: "Crucial events occurred here.",
    sources: [],
  },
  {
    id: "avengers-compound",
    name: "Avengers Compound",
    description: "A significant place.",
    planet: "Unknown",
    universe: "Earth-616",
    significance: "Crucial events occurred here.",
    sources: [],
  },
  {
    id: "asgard",
    name: "Asgard",
    description: "A significant place.",
    planet: "Unknown",
    universe: "Earth-616",
    significance: "Crucial events occurred here.",
    sources: [],
  },
  {
    id: "wakanda",
    name: "Wakanda",
    description: "A significant place.",
    planet: "Unknown",
    universe: "Earth-616",
    significance: "Crucial events occurred here.",
    sources: [],
  },
  {
    id: "kamar-taj",
    name: "Kamar-Taj",
    description: "A significant place.",
    planet: "Unknown",
    universe: "Earth-616",
    significance: "Crucial events occurred here.",
    sources: [],
  },
  {
    id: "sanctum-sanctorum",
    name: "Sanctum Sanctorum",
    description: "A significant place.",
    planet: "Unknown",
    universe: "Earth-616",
    significance: "Crucial events occurred here.",
    sources: [],
  },
  {
    id: "quantum-realm",
    name: "Quantum Realm",
    description: "A significant place.",
    planet: "Unknown",
    universe: "Earth-616",
    significance: "Crucial events occurred here.",
    sources: [],
  },
  {
    id: "tva-headquarters",
    name: "TVA Headquarters",
    description: "A significant place.",
    planet: "Unknown",
    universe: "Earth-616",
    significance: "Crucial events occurred here.",
    sources: [],
  },
  {
    id: "knowhere",
    name: "Knowhere",
    description: "A significant place.",
    planet: "Unknown",
    universe: "Earth-616",
    significance: "Crucial events occurred here.",
    sources: [],
  },
  {
    id: "xandar",
    name: "Xandar",
    description: "A significant place.",
    planet: "Unknown",
    universe: "Earth-616",
    significance: "Crucial events occurred here.",
    sources: [],
  },
  {
    id: "titan",
    name: "Titan",
    description: "A significant place.",
    planet: "Unknown",
    universe: "Earth-616",
    significance: "Crucial events occurred here.",
    sources: [],
  },
  {
    id: "vormir",
    name: "Vormir",
    description: "A significant place.",
    planet: "Unknown",
    universe: "Earth-616",
    significance: "Crucial events occurred here.",
    sources: [],
  },
  {
    id: "madripoor",
    name: "Madripoor",
    description: "A significant place.",
    planet: "Unknown",
    universe: "Earth-616",
    significance: "Crucial events occurred here.",
    sources: [],
  },
  {
    id: "ta-lo",
    name: "Ta Lo",
    description: "A significant place.",
    planet: "Unknown",
    universe: "Earth-616",
    significance: "Crucial events occurred here.",
    sources: [],
  },
];
